### ISSUE TITLE
[BUG] Commands hang indefinitely using Azure Storage Blob on DataBricks

### ISSUE THREAD

**Issue by david-nguyen** [Azure/azure-sdk-for-java#6142]
**Describe the bug**
Using Azure Storage Blob 12.0.0, Commands hang indefinitely when executing commands that have the blob client connect to Azure on DataBricks. I've tested the same script locally and it works - it seems like some sort of connection is blocked.

***Exception or Stack Trace***
The command hangs indefinitely and nothing is shown in the cluster log in DataBricks.

**To Reproduce**
- Using com.azure / azure-storage-blob / 12.0.0 library from Maven
- Run commands to establish blob client
- Perform action against blob client

***Code Snippet***

     val blobClient = new BlobClientBuilder()
     .endpoint("https://*.blob.core.windows.net/")
     .connectionString(connectionString)
     .containerName(storageContainer)
     .blobName("load/test2.csv")
     .buildClient()

     val blobTestClient = new BlobClientBuilder()
    .endpoint("https://*.blob.core.windows.net/")
    .connectionString(connectionString)
    .containerName(storageContainer)
    .blobName("move/test2.csv")
    .buildClient()

    println(blobTestClient.getProperties().getBlobSize())

**Expected behavior**
The command executes and blob file is copied.

**Screenshots**
![image](https://user-images.githubusercontent.com/1424016/68044618-4fc6bb80-fc9d-11e9-81b6-45ecb020e7c9.png)

**Setup (please complete the following information):**
- Cluster info: 5.5 LTS Spark 2.4.3. Scala 2.11
- 32GB mem, 16 core, 2dbu
- com.azure / azure-storage-blob / 12.0.0 library installed on cluster
- have blob exist

**Additional context**
Script works fine locally but will not work on the Databricks environment.

**Information Checklist**
Kindly make sure that you have added all the following information above and check off the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by aravish** [comment]
Exception inside Databricks

19/11/01 22:08:01 WARN AbstractChannelHandlerContext: An exception 'java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpUtil.formatHostnameForHttp(Ljava/net/InetSocketAddress;)Ljava/lang/String;' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpUtil.formatHostnameForHttp(Ljava/net/InetSocketAddress;)Ljava/lang/String;
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.resolveHostHeaderValue(HttpClientConnect.java:593)
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:552)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:429)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:473)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:525)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:434)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:62)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:414)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1480)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1318)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aravish** [comment]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:81)
	at reactor.core.publisher.Mono.block(Mono.java:1663)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:94)
	at com.azure.storage.blob.specialized.BlobClientBase.getPropertiesWithResponse(BlobClientBase.java:560)
	at com.azure.storage.blob.specialized.BlobClientBase.getProperties(BlobClientBase.java:538)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1690938166956809:1)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1690938166956809:53)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1690938166956809:55)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1690938166956809:57)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw$$iw.<init>(command-1690938166956809:59)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw$$iw.<init>(command-1690938166956809:61)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw$$iw.<init>(command-1690938166956809:63)
	at linecef297b8b6904f2689cf7d768f44973231.$read$$iw.<init>(command-1690938166956809:65)
	at linecef297b8b6904f2689cf7d768f44973231.$read.<init>(command-1690938166956809:67)
	at linecef297b8b6904f2689cf7d768f44973231.$read$.<init>(command-1690938166956809:71)
	at linecef297b8b6904f2689cf7d768f44973231.$read$.<clinit>(command-1690938166956809)
	at linecef297b8b6904f2689cf7d768f44973231.$eval$.$print$lzycompute(<notebook>:7)
	at linecef297b8b6904f2689cf7d768f44973231.$eval$.$print(<notebook>:6)
	at linecef297b8b6904f2689cf7d768f44973231.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:679)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:632)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:368)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:345)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:345)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rickle-msft** [comment]
@alzimmermsft @jianghaolu @anuchandy Have you guys seen this error from HttpUtil before? It doesn't look to be anything in core or storage, but I thought I'd double check.

Based on getting a NoSuchMethodError, and since you're running it locally just fine, I tend to think it looks like this could be due to a Maven/build problem. I would recommend you take a look through [this post](https://stackoverflow.com/questions/35186/how-do-i-fix-a-nosuchmethoderror) and try some of the strategies related to ensuring you have the correct versions of your dependencies and that they are properly installed. Let us know if you are unable to find a solution there.

**Comment by david-nguyen** [comment]
thanks for the exception I'm guessing that means that there is a conflict of the netty library included with databricks versus azure storage blob then.

io.netty | netty | 3.9.9.Final
-- | -- | --
io.netty | netty-all | 4.1.17.Final

io.netty 3.x does not come with http util

**Comment by aravish** [comment]
@david-nguyen 
Can you please try attaching io.netty 4.x in Databricks?

**Comment by david-nguyen** [comment]
> @david-nguyen
> Can you please try attaching io.netty 4.x in Databricks?

Sorry I was wrong, the netty all package has the missing method.

**Comment by david-nguyen** [comment]
> @david-nguyen
> Can you please try attaching io.netty 4.x in Databricks?

I don't think this can be easily I achieved, did not have much success including an update netty-all package. Also tried the spark config `userclasspathfirst`

**Comment by aravish** [comment]
@rickle-msft 
Azure Storage Blob is installing 4.1.42 version of the jars on Databricks

azure-storage-blob-12.0.0
netty-handler-proxy-4.1.42.Final.jar
netty-resolver-4.1.42.Final.jar
netty-buffer-4.1.42.Final.jar
netty-transport-4.1.42.Final.jar
netty-transport-native-epoll-4.1.39.Final.jar
netty-codec-4.1.42.Final.jar
netty-common-4.1.42.Final.jar
netty-codec-http-4.1.42.Final.jar
netty-codec-socks-4.1.42.Final.jar
netty-transport-native-unix-common-4.1.39.Final.jar
netty-handler-4.1.42.Final.jar

whereas Databricks is loading 4.1.17 which is causing the conflict.
[Loaded io.netty.handler.codec.http.HttpMethod from file:/databricks/jars/spark--maven-trees--spark_2.4--io.netty--netty-all--io.netty__netty-all__4.1.17.Final.jar]

Per Databricks there is not an easy way to pin specific version as this might break other functionality.

Do you have any other suggestions or recommendations?

**Comment by rickle-msft** [comment]
Because these dependencies are set by azure core, I have passed on this issue to someone on that team so they can advise on how to resolve those depdencies safely. They should be following up here soon.

**Comment by joshfree** [comment]
@anuchandy could you please assist with this maven build dependency issue?  Can you add this to the Java repo wiki (FAQ / getting help section) with some instructions / examples for diagnosing and fixing this type of maven build issue as others will run into this in the future.

Thanks

**Comment by anuchandy** [comment]
The reactor-netty 0.9.0-RELEASE cannot work with netty version 4.1.17 that Databricks is loading, this version of Netty is missing a method that reactor-netty requires. The only option I see here is to force Databricks to load netty-4.1.42. We need to check with Databrick team team to see how to do it. 

@aravish do you have any contact in Databricks that we can talk to?

**Comment by anuchandy** [comment]
It seems we cannot down grade to older version of `reactor-netty` as older versions has stability issue (e.g. 0.8.x version has connection leaking). 

Data bricks is using latest version of spark https://search.maven.org/artifact/org.apache.spark/spark-core_2.11/2.4.4/jar which is pinned to netty-4.1.17.

**Comment by abizeradenwala** [comment]
Yes we are already using latest version of spark which includes 4.1.17 netty version.

https://docs.azuredatabricks.net/release-notes/runtime/6.0.html#installed-java-and-scala-libraries-scala-211-cluster-version

With latest DBR version netty-all was upgraded from 4.1.17 to 4.1.39 but that still doesn't match the version netty-4.1.42 which is needed here.

https://docs.azuredatabricks.net/release-notes/runtime/6.1.html#improvements

**Comment by aravish** [comment]
@anuchandy, Abizer is from Databricks. If you need any assistance from Databricks, he will be able to help.

**Comment by anuchandy** [comment]
thank you @aravish for helping here.

@abizeradenwala thanks a lot for sharing this info. 

If I understand correctly - even though spark 2.4.4 is declared netty-4.1.17 as dependency, the DB runtime 6.1 (that is hosting spark 2.4.4) override it to netty-4.1.39, so that spark and other app running on the cluster picks netty-4.1.39. Please correct me if I'm wrong.

I'm almost sure that netty-4.1.42.Final (storage -> azure-core -> netty-4.1.42.Final) is compatible with netty-4.1.39. The reason is azure-core uses reactor-netty-0.9.0-RELEASE and reactor-netty declared netty-4.1.39 as dependency but we override it with netty-4.1.42.Final in azure-core, we tested that there is no regression when upgrading from netty-4.1.39 to netty-4.1.42.

@david-nguyen this means your setup should work with DBR 6.1 but let's wait for @abizeradenwala to confirm on my above assumption related to DBR 6.1.

**Comment by aravish** [comment]
@anuchandy, 
Tried with DBR 6.1, getting below error now, I can confirm netty 4.1.39 is being loaded.
/databricks/jars/spark--maven-trees--spark_2.4--io.netty--netty-all--io.netty__netty-all__4.1.39.Final.jar

**Error Stack:**

19/11/05 14:04:35 WARN AbstractChannelHandlerContext: An exception 'java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.createContextual(JSR310DateTimeDeserializerBase.java:79)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.createContextual(InstantDeserializer.java:241)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2764)
	at com.azure.core.implementation.serializer.jackson.JacksonAdapter.deserialize(JacksonAdapter.java:192)
	at com.azure.core.implementation.serializer.HttpResponseHeaderDecoder.lambda$decode$0(HttpResponseHeaderDecoder.java:36)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.MonoProcessor.add(MonoProcessor.java:457)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:370)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.ignoreDone(MonoIgnoreThen.java:190)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onComplete(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:397)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:197)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:345)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by anuchandy** [comment]
@aravish thanks for trying, so netty version mismatch is fixed. 

The Jackson version that azure-core uses is 2.10.0. Error indicate that platform is loading a different version of Jackson (either baked into runtime or as a transitive dependency) which does not have the types/methods available in 2.10.0.

Usually we can force maven to pull specific version of packages by adding them explicitly in the app's pom file. Basically in your pom, we need to add all Jackson dependencies listed in the below link with 2.10.0 for ${jackson.version}.

https://github.com/Azure/azure-sdk-for-java/blob/769753df5ac1c67f5b2431d6a6adc0f7c3227e90/parent/pom.xml#L235 

This works only if the platform/DBR allows application to override them, it seems like netty-4.1.39.Final DBR comes with 2.6.0 Jackson packages preinstalled.

**Comment by aravish** [comment]
@abizeradenwala 

Any thoughts?

This is what we are now getting with DBR 6.1

19/11/05 20:30:55 ERROR ChannelOperationsHandler: [id: 0xb75a115b, L:/10.139.64.9:35910 - R:aravishhadooprsgrp.blob.core.windows.net/20.38.104.100:443] Error was received while reading the incoming data. The connection will be closed.
java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.createContextual(JSR310DateTimeDeserializerBase.java:79)

**Comment by anuchandy** [comment]
@david-nguyen just to give you an update, DB team and SDK team are discussing this issue internally and we will update the status here once there is a conclusion.

**Comment by abizeradenwala** [comment]
Thanks @anuchandy Good to see original issue is resolved now . New mismatch is this being discussed with DB engineering via private channel ?

@Arvind-Ravi  Can you do same test discussed on the case and confirm method are loading from 2.6.0 Jackson packages while Jackson version that azure-core uses is 2.10.0 and hence specific method is not present in older version ? Please update the case if Anu is not in contact with engineering and we will see what can be done .

**Comment by aravish** [comment]
@abizeradenwala,

I included you on the internal mail thread with Engineering.

I can confirm Databricks is loading 2.6.7
spark--maven-trees--spark_2.4--com.fasterxml.jackson.datatype--jackson-datatype-joda--com.fasterxml.jackson.datatype__jackson-datatype-joda__2.6.7.jar

While storage SDK is referencing 2.10.0 version of below
<dependency>
	<groupId>com.fasterxml.jackson.datatype</groupId>
	<artifactId>jackson-datatype-jsr310</artifactId>
	<version>${jackson.version}</version>
</dependency>

@anuchandy, Please confirm.

**Comment by anuchandy** [comment]
@aravish yes storage uses Jackson 2.10.0.

@abizeradenwala all the packages and it's versions that sdk transitively pull can be found here: https://github.com/Azure/azure-sdk-for-java/blob/master/parent/pom.xml

**Comment by anuchandy** [comment]
Our recommendation is to shade the application with all dependencies. We've added a section in our FAQ- https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#how-to-manage-dependencies-of-my-application-running-on-azure-data-bricks

**Comment by joshfree** [comment]
Closing this issue from November 2019 as the JAR shading instructions have been documented at  https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#how-to-manage-dependencies-of-my-application-running-on-azure-data-bricks and also shared with the Databricks team.
