### ISSUE TITLE
[BUG] TableServiceClient.createTableIfNotExistsWithResponse() with wrong error handling and response code

### ISSUE THREAD

**Issue by DragonLi-Mi** [Azure/azure-sdk-for-java#39364]
**Describe the bug**
I can't use the this function. The response is a really confusing. 
I want to call this function and write some data into the new created table. 
It only retruns a simple reponse code. 
For 409, it can be "The table specified already exists" or "The specified table is being deleted." but the infomation only in log! I can't decide what to do with the simple 409. It is much different for the caller. 

Besides,  it throw an InterruptedException when it hit an timeout issue. The meaningful error message and exception was hided!
**To Reproduce**
class java.lang.InterruptedException cannot be cast to class java.lang.RuntimeException (java.lang.InterruptedException and java.lang.RuntimeException are in module java.base of loader 'bootstrap')

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
the function createTableIfNotExistsWithResponse should have an attribute to let the caller decide to just use the table or create another one.  it should throw valid exception. 
**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by DragonLi-Mi** [comment]
blow function very easily to hit InterruptedException after upgrading from 12.3.19 to 12.3.20
```
        ListTablesOptions options = new ListTablesOptions();
        options.setFilter(String.format("TableName" + FilterConstants.EQ + "'%s'", tableName));
        return tableServiceClient.listTables(options, Duration.ofSeconds(60), Context.NONE)
            .stream().anyMatch(tableItem -> tableItem.getName().equals(tableName));
```

**Comment by DragonLi-Mi** [comment]
Can you put thee.detailMessage into the null place? 
![image](https://github.com/Azure/azure-sdk-for-java/assets/4321063/c0101818-f3e2-4aff-8d2e-7d675ec08881)

**Comment by alzimmermsft** [comment]
@jairmyree could you take a look at this issue

**Comment by jairmyree** [comment]
Hello @DragonLi-Mi. Thank you for reaching out. After reviewing your issue I'd like to point out that the documentation does not guarantee any particular behavior as far as the handling of 409 status-code responses. With that being said, I will take your suggestions about changing the response value for 409 status-codes to the greater Tables team for feedback. Thank you very much.

**Comment by jairmyree** [comment]
@DragonLi-Mi Thank you for identifying the potential confusion with the 409-status-code swallowing for `createTableIfNotExists`. For clarity, I've split it off into its own issue which you can track here: https://github.com/Azure/azure-sdk-for-java/issues/39389

As for the response value, to remain aligned with the SDKs design, we will continue to swallow the 409-status-code responses for instances where the table already exists.

Thank you very much.
