### ISSUE TITLE
[FEATURE REQ] azure-spring-cloud-feature-management-web:2.8.0 cannot work with Spring Boot 3.0.0.M3

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30465]
**Is your feature request related to a problem? Please describe.**
The latest Azure Spring Cloud Feature Management Web (azure-spring-cloud-feature-management-web:2.7.0) can work with Spring Boot 2.7.x, it's incompatible with the milestone version 3.0.0-M3, which the Spring will release its official version soon.

Found exception : `java.lang.NoClassDefFoundError: org/springframework/web/servlet/handler/HandlerInterceptorAdapter`
This interface `org.springframework.web.servlet.handler.HandlerInterceptorAdapter` has been deprecated since `spring-webmvc` 5.3, and removed in `spring-webmvc` 6.0.0.M4.

**Describe the solution you'd like**
Should use an alternate interface.

**Describe alternatives you've considered**
Compatible with Spring Boot 3.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by moarychan** [comment]
Hi @mrm9084, could you help to improve this code compatibility with Spring Boot 3.0.0-M?

**Comment by moarychan** [comment]
Hi @mrm9084 , thanks for your update on the Teams!
We hope that the source code modification is ready this month, and the release should be done next month. Currently, the Spring Boot milestone version(M4) is now available for a long time on the website https://start.spring.io/,  our artifacts are not compatible for use, we should improve the user experience in Spring Cloud Azure so that it can be used normally at least. 

We decide to use a new branch [feature/spring-cloud-azure-6.x](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-cloud-azure-6.x) to target our goal. It will be used as a daily development branch together with the `main` branch, and different versions of the release will be done separately.

**Comment by mrm9084** [comment]
@moarychan I don't think that timeline works for us. Currently we have:
https://github.com/Azure/azure-sdk-for-java/tree/feature/azconfig-spring/DynamicFeature
Which is in public preview with no eta, and it contains the 4.0 changes for the feature management libraries.

https://github.com/mrm9084/azure-sdk-for-java/tree/AppConfig4.0
This is everything else, but is blocked by geo-replication:
https://github.com/Azure/azure-sdk-for-java/pull/30084

and the rest of the work on it being finished. The number of breaking changes and big features added between them would make any M release meaningless as it wouldn't actually be a milestone of what will be released.

@saragluna

**Comment by moarychan** [comment]
@mrm9084 , I got it, we will exclude Spring Cloud Aapconfiguration parts, these artifacts may be released in the second M version.

**Comment by mrm9084** [comment]
@moarychan, 5.1.0 has been released. It does have a few breaking changes if you are moving from a 2.x version, not from the 4.x version. If you are updating from 2.x you can reference https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-convert-to-the-new-spring-boot
