### ISSUE TITLE
[BUG] After upgrading oauth2-oidc-sdk to 9.5.1 getting this error java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes

### ISSUE THREAD

**Issue by narigala** [Azure/azure-sdk-for-java#21333]
**Describe the bug**
We are currently using the oauth2-oidc-sdk 5.30 version but as it is vulnerable upgraded to 9.5.1 but we are not able to connect to Azure. getting this error 

***Exception or Stack Trace***
ava.lang.RuntimeException: java.io.IOException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)

**To Reproduce**
Upgrade the oauth2-oidc-sdk  from 5.30 version to 9.5.1

***Code Snippet***
<dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>9.5.1</version>
            <scope>runtime</scope>
        </dependency>

**Expected behavior**
It should work as usual, without any errors, we should be able to connect to Azure from our application as we were using older version

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ x Setup information Added

**Comment by joshfree** [comment]
Hi @narigala which SDK name and version are you using which references 5.3.0 oauth2-oidc-sdk?

Please note you can reference the auzre-sdk-bom (https://mvnrepository.com/artifact/com.azure/azure-sdk-bom) or the azure-spring-boot-bom (https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-bom) which will also include much newer versions of this dependency.
