### ISSUE TITLE
[BUG] azure-spring-boot-starter-keyvault-secrets doesn't work with SpringBoot 2.1.8.RELEASE

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/azure-sdk-for-java#19322]
**Describe the bug**
when I created a springboot project, add Azure Key Vault, it shows it requires Spring Boot >= 2.0.0.RELEASE and < 2.4.0.M1.
but when tried 2.1.8.RELEASE, it shows some errors.

***Exception or Stack Trace***
15:23:15.343 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: reactor.netty.http.client.HttpClient.doAfterResponseSuccess(Ljava/util/function/BiConsumer;)Lreactor/netty/http/client/HttpClient;
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:101)
	at com.azure.core.http.netty.implementation.ReactorNettyClientProvider.createInstance(ReactorNettyClientProvider.java:14)
	at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:39)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:39)
	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:161)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:104)
	at com.azure.spring.keyvault.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:94)
	at com.azure.spring.keyvault.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:47)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)

**To Reproduce**
I followed this document: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yiliuTo** [comment]
Hi @rachelxj-ms , this is due to the versions of our starter and springboot you use don't match with each other. Could you please check if you use springboot 2.1.8.release and key vault starter 3.1.0 together? 

The active springboot versions we now support is 2.2.x and 2.3.x, you can refer to [our spring boot dependency mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Boot-Dependency-Mapping#version-schema-in-azure-sdk-for-java-repo) and choose ones that fit you.

**Comment by rachelxj-ms** [comment]
Yes, I'm using azure-spring-boot-starter-keyvault-secrets 3.1.0 and springboot 2.1.8.release

**Comment by yiliuTo** [comment]
Then would you try with springboot 2.2.x.release or 2.3.x.release?

**Comment by rachelxj-ms** [comment]
I know 2.3.5 can work with 3.1.0, just the warning from https://start.spring.io/ is not that clear enough. :)
![image](https://user-images.githubusercontent.com/66855967/109091609-18143a80-7750-11eb-90eb-c722b03b15f5.png)

**Comment by yiliuTo** [comment]
Oh, thanks for your reporting! we will create an issue in spring-io repo for this.

**Comment by Shanbw** [comment]
I solved this problem by upgrading the netty version

My running environment：Springboot 2.1.6.RELEASE

Solution steps：
1、add dependencies
```
        <dependency>
		<groupId>io.projectreactor.netty</groupId>
		<artifactId>reactor-netty</artifactId>
		<version>1.0.14</version>
	</dependency>

         <dependency>
		<groupId>io.projectreactor</groupId>
		<artifactId>reactor-core</artifactId>
		<version>3.4.13</version>
	</dependency>
```

2、Modify the default version of springboot
```
        <properties>
		<jackson.version>2.11.0</jackson.version>
		<netty.version>4.1.72.Final</netty.version>
	</properties>
```
