### PR TITLE
Release azure-cosmos-spark 4.47.0

### PR DESCRIPTION
**Pull request by tvaron3**
## Release azure-cosmos-spark 4.47.0

Version bumps and CHANGELOG updates for:
- azure-cosmos-spark_3-3_2-12 4.47.0
- azure-cosmos-spark_3-4_2-12 4.47.0
- azure-cosmos-spark_3-5_2-12 4.47.0
- azure-cosmos-spark_3-5_2-13 4.47.0
- azure-cosmos-spark_4-0_2-13 4.47.0

### Features Added
- Added support for change feed with `startFrom` point-in-time on merged partitions by enabling the `CHANGE_FEED_WITH_START_TIME_POST_MERGE` SDK capability in the azure-cosmos SDK. - See [PR 48752](https://github.com/Azure/azure-sdk-for-java/pull/48752)

### Bugs Fixed
- Fixed an issue where `readContainerThroughput` was always called even when `targetThroughput` is explicitly configured, requiring unnecessary `throughputSettings/read` permission for AAD principals. - See [PR 48800](https://github.com/Azure/azure-sdk-for-java/pull/48800)

### Other Changes
- Updated azure-cosmos CHANGELOG to reclassify the startFrom fix as a feature with PR link
- Updated README compatibility tables with 4.47.0 rows
- Updated quick-start.md connector links to 4.47.0
- Propagated version to dependent pom files (account-data-resolver-sample, fabric-cosmos-spark-auth_3)

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]

File: sdk/cosmos/azure-cosmos-spark_3-3_2-12/CHANGELOG.md [hunk 1]
```diff
@@ -1,16 +1,13 @@
 ## Release History
 
-### 4.47.0-beta.1 (Unreleased)
+### 4.47.0 (2026-04-16)
 
 #### Features Added
-
-#### Breaking Changes
+* Added support for change feed with `startFrom` point-in-time on merged partitions by enabling the `CHANGE_FEED_WITH_START_TIME_POST_MERGE` SDK capability in the azure-cosmos SDK. - See [PR 48752](https://github.com/Azure/azure-sdk-for-java/pull/48752)
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos-spark_3-3_2-12/CHANGELOG.md:6]: Please add a link to the static initializer PR as well here

File: sdk/cosmos/azure-cosmos-spark_4-0_2-13/README.md [hunk 2]
```diff
@@ -20,6 +20,7 @@ https://github.com/Azure/azure-sdk-for-java/issues/new
 #### azure-cosmos-spark_4-0_2-13
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos-spark_4-0_2-13/README.md:20]: Let us add a secrtion for known issue (Spark Structured STreaming does not work with DBX 17.3 here please

File: sdk/cosmos/azure-cosmos-spark_4-0_2-13/README.md [hunk 3]
```diff
@@ -178,14 +183,19 @@ to use the same version of Scala that Spark was compiled for.
 | 4.43.1    | 3.5.0                    | [17]                  | 2.13                      | 16.4 LTS                      | TBD                       |
 | 4.43.0    | 3.5.0                    | [17]                  | 2.13                      | 16.4 LTS                      | TBD                       |
 
+### Known Issues
+
+#### Spark Structured Streaming does not work with Databricks Runtime 17.3
+Databricks Runtime 17.3 uses Spark 4.0.0-preview2, which relocated the internal class `org.apache.spark.sql.connector.read.streaming.SparkDataStream` to a different package starting in Spark 4.1. This causes a `NoClassDefFoundError` when using Spark Structured Streaming with the Cosmos DB Spark connector on DBR 17.3. This issue affects all Spark connectors that depend on this internal API. We are tracking the upstream Spark issue and will provide a fix once a public API is available.
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos-spark_4-0_2-13/README.md]: Sorry - never mind - Annie has a fix for this - and the fix will unblock us on DBX 17.3. So, we can remove this comment but should wasit for Annies fix to be merged I think?

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks!
