### ISSUE TITLE
[BUG] Active Directory starter 6.1.0 ClassNotFoundException: com.nimbusds.oauth2.sdk.util.StringUtils

### ISSUE THREAD

**Issue by dnijssen** [Azure/azure-sdk-for-java#47600]
**Describe the bug**
Between Spring Cloud Azure Dependencies 6.0.0 -> 6.1.0 we stumbled upon a `ClassNotFoundException: com.nimbusds.oauth2.sdk.util.StringUtils` 

***Exception or Stack Trace***
```java
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/util/StringUtils
	at com.azure.spring.cloud.autoconfigure.implementation.aad.security.properties.AadAuthorizationServerEndpoints.<init>
```

**Additional context**
We just have a simple Spring Boot project at our side, with the following Security related dependencies;

```kts
implementation("org.springframework.boot:spring-boot-starter-security")
implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server")
implementation("com.azure.spring:spring-cloud-azure-starter-active-directory")
```

Works with Spring Boot 3.5.9 and Spring Azure Cloud Depenencies 6.0.0, but when upgrading to Spring Azure Cloud Dependencies 6.1.0 it breaks

**Comment by rujche** [comment]
Hi, @dnijssen. Thank for reaching out.

## 1. Root cause analysis.
1. The `com.nimbusds.oauth2.sdk.util.StringUtils` was in this artifact: `oauth2-oidc-sdk`
   > <img width="1920" height="1149" alt="Image" src="https://github.com/user-attachments/assets/5c43322d-c9bd-4dc0-b065-4aab42c98c6d" />

2. When use 6.0.0, the dependency is added by `azure-identity` -> `masl4j` -> `oauth2-oidc-sdk`. The path from `spring-security-oauth2-client` won't take effect because it's optional and your project didn't have this dependency.
   > <img width="1920" height="1149" alt="Image" src="https://github.com/user-attachments/assets/d359847e-1b1a-4ba9-9c91-b6fb8520edca" />
   > <img width="1920" height="1149" alt="Image" src="https://github.com/user-attachments/assets/cd644c63-27db-4121-8d0a-5c7c822dcbfd" />

3. When use 6.1.0, the dependency path from `azure-identity` is missting.
   > <img width="1920" height="1149" alt="Image" src="https://github.com/user-attachments/assets/0a0fdd6b-49f2-47fb-907c-f51fbd8cc751" />

## 2. Workaround
You can do like this as workaround: Adding this dependency in your project:
```gradle
implementation("com.nimbusds:oauth2-oidc-sdk:9.43.6")
```

## 3. Fix in Spring Cloud Azure side

Use `StringUtils` from `spring-core` instead. In a spring-boot project, it will always contains `spring-core` dependency. 
> <img width="1920" height="1149" alt="Image" src="https://github.com/user-attachments/assets/e6472a49-d5ce-4e49-98fa-529a4c90bb01" />

PR is coming soon. The diff will be like this:
```shell
$ git diff
diff --git a/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/aad/security/properties/AadAuthorizationServerEndpoints.java b/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/aad/security/properties/AadAuthorizationServerEndpoints.java
index ca5c53af3e4..fd098c6d738 100644
--- a/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/aad/security/properties/AadAuthorizationServerEndpoints.java
+++ b/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/aad/security/properties/AadAuthorizationServerEndpoints.java
@@ -3,7 +3,8 @@
 
 package com.azure.spring.cloud.autoconfigure.implementation.aad.security.properties;
 
-import com.nimbusds.oauth2.sdk.util.StringUtils;
+
+import org.springframework.util.StringUtils;
 
 /**
  * Used to get endpoints for Microsoft Identity authorization server.
@@ -27,7 +28,7 @@ public class AadAuthorizationServerEndpoints {
      * @param tenantId the tenant ID
      */
     public AadAuthorizationServerEndpoints(String baseUri, String tenantId) {
-        if (StringUtils.isBlank(baseUri)) {
+        if (!StringUtils.hasText(baseUri)) {
             baseUri = DEFAULT_BASE_URI;
         }
         this.baseUri = addSlash(baseUri);
```

@copilot, create the PR according to above diff.

**Comment by dnijssen** [comment]
@rujche Will the fix be included in 7.0.0 as well? Because it is currently missing in 7.0.0-beta.1

**Comment by rujche** [comment]
> [@rujche](https://github.com/rujche) Will the fix be included in 7.0.0 as well? Because it is currently missing in 7.0.0-beta.1

@dnijssen Yes, it will be fixed in 7.0.0.
