### PR TITLE
Fixing ordering problem when sending messages in a batch

### LINKED ISSUE #25112: [BUG] ServiceBusMessageBatch does not preserve message order reliably
**Describe the bug**
When the ServiceBusMessageBatch class is used to send batches of ServiceBus messages, the order of adding the messages to the ServiceBusMessageBatch object is not reliably the order the messages are added to the destination queue.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
It was confirmed by testing and comparing the resulting order of the messages on the queue.  When not using ServiceBusMessageBatch the send order was reliably the message order on the queue, but when using ServiceBusMessageBatch the order was frequently not preserved, leading to erroneous processing by the received.

***Code Snippet***
I have a simple wrapper around the ServiceBus client that enable switching between batched sends and un-batched sends - the actual send method looks like this:
        void sendMessage(ServiceBusMessage serviceBusMessage){
            if(!batchingEnabled) {
                log.trace("Send single service bus messages to {}", getNameQualifier());
                senderClient.sendMessage(serviceBusMessage);
            } else {
                if(!serviceBusMessageBatch.get().tryAddMessage(serviceBusMessage)){
                    flush();
                    if(!serviceBusMessageBatch.get().tryAddMessage(serviceBusMessage)){
                        String msg = String.format("Unable to add SB message to batch - too large - %d?", serviceBusMessage.getBody().toBytes().length);
                        ServiceBusSink.this.senderClient = null;
                        throw new RuntimeException(msg);
                    }
                }
            }
        }

**Expected behavior**
Batches of messages assembled using ServiceBusMessageBatch should be written to the destination queue in the order in which they are added to the ServiceBusMessageBatch object.
**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux in K8S Container
 - IDE: n/a
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.4.2
 - Java version: 11
 - App Server/Environment: AKS Pod
 - Frameworks: Micronaut,

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

### LINKED ISSUE #25599: [BUG] Invalid message order in batch sending
After upgrading azure-messaging-servicebus lib from 7.0.1 to 7.3.0, I noticed that batch sending is reordering messages in Service Bus. I suppose this is due to the use of parallelStream() in the ServiceBusMessageBatch.sendInternal() method. This has been changed in the commit: https://github.com/Azure/azure-sdk-for-java/commit/a9b28ec39515b1aa112d6ef211cac2455d729afa#diff-bfbb3d6ac91c080eaa27ee29c12058246337099dcd205dc86a625dee08bfa17e.
I expect the order of the messages in the list for batch should be the same as in Service Bus.

### PR DESCRIPTION
**Pull request by ki1729**
# Description
When sending a Collection of messages, the order of insertion into collection should be the order of messages in SB. This was not the case due to inclusion of parallel stream to potentially increase throughput locally. Fixed this by removing parallel stream  in construction of both the proton message and the ServiceBusMessageBatch object.

Fixes #25599
Fixes #25112

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by conniey — APPROVED** [review]
:shipit:

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java [hunk 1]
```diff
@@ -723,7 +723,7 @@ public void close() {
 
         AtomicReference<Context> sharedContext = new AtomicReference<>(Context.NONE);
         final List<org.apache.qpid.proton.message.Message> messages = Collections.synchronizedList(new ArrayList<>());
-        batch.getMessages().parallelStream().forEach(serviceBusMessage -> {
+        batch.getMessages().forEach(serviceBusMessage -> {
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java:726]: Can we use `map().collect(Collectors.toList()` instead?
