### ISSUE TITLE
Exception in thread "main" java.lang.LinkageError: Package versions: jackson-annotations=2.10.1, jackson-core=2.10.1, jackson-databind=2.10.1, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=unknown, azure-core=1.26.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

### ISSUE THREAD

**Issue by Jai783** [Azure/azure-sdk-for-java#27584]
**Describe the bug**
Error message when executing : 

Exception in thread "main" java.lang.LinkageError: Package versions: jackson-annotations=2.10.1, jackson-core=2.10.1, jackson-databind=2.10.1, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=unknown, azure-core=1.26.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

**To Reproduce**

***Code Snippet***
I have used the similar code as mentioned in the link - (https://github.com/Azure/azure-sdk-for-java/issues/10539)
![image](https://user-images.githubusercontent.com/101332881/157658970-2be4f812-b50e-46b3-8760-cd65b298f011.png)

**Expected behavior**
Calling DefaultAzureCredential.build() should succeed, and would be used to authenticate to AKV

**Setup (please complete the following information):**
 - OS: Windows10
 - IDE: Eclipse
 - Java version: 1.8.0_74

**MyPOM file is as below.** 
![image](https://user-images.githubusercontent.com/101332881/157661112-506eea00-2413-48a6-8e17-ca063696ce8f.png)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@pallavit could you please follow up with @Jai783?

**Comment by pallavit** [comment]
Absolutely. Thanks for reporting the issue. I will take a look at it and get back to you.

One of the things that I noticed from the error you shared was 
![image](https://user-images.githubusercontent.com/10713359/158249025-91680968-da11-41c0-9d41-e7d987db8bc2.png)

which is indicating azure-core 1.26.0 however you are the BOM 1.0.1 which has azure-core 1.5.1. How are you loading the new core? Would you mind upgrading to the latest core and BOM - https://repo1.maven.org/maven2/com/azure/azure-sdk-bom/1.1.1/azure-sdk-bom-1.1.1.pom and include all the dependencies from it and see whether you are getting issues from it?

**Comment by Jai783** [comment]
@pallavit Thanks for your reply. The linkage error disappeared after I updated the version of BOM to 1.1.1 and azure-core to 1.5.1 . 
However I am getting this new error , I hope I need to set AZURE_CLIENT_ID in my server environment variable.  Please let me know if there is anything else apart from AZURE_CLIENT_ID to be set in my environment variable. Thanks.

47 [main] ERROR com.azure.identity.EnvironmentCredential - Azure Identity => ERROR in EnvironmentCredential: Missing required environment variable AZURE_CLIENT_ID
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: reactor/core/publisher/Mono
        at com.azure.identity.implementation.IdentityClient.<init>(IdentityClient.java:168)
        at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:139)
        at com.azure.identity.ManagedIdentityCredential.<init>(ManagedIdentityCredential.java:70)
        at com.azure.identity.DefaultAzureCredentialBuilder.getCredentialsChain(DefaultAzureCredentialBuilder.java:129)
        at com.azure.identity.DefaultAzureCredentialBuilder.build(DefaultAzureCredentialBuilder.java:123)
        at com.scb.pvb.sw.dbutils.BCPImpl.runsqlcmd(BCPImpl.java:83)
        at com.scb.pvb.sw.dbutils.BCP.execCmd(BCP.java:59)
        at com.scb.pvb.sw.dbutils.BCP.main(BCP.java:81)
Caused by: java.lang.NoClassDefFoundError: reactor/core/publisher/Mono
