### PR TITLE
Fix Spring sub-level event-hub-name override and EventContext checkpoint offsetString propagation

### LINKED ISSUE #43593: [BUG] The base level `event-hub-name` property should be overridden when sub-level `event-hub-name` property configured
**Describe the bug**

When using the `spring-cloud-azure-starter-eventhubs` dependency, if I specify the properties in the application.yaml as follows, I think the expected result is that the `event-hub-name` in the `producer` and `consumer` section will override the base `event-hub-name`, that is, the application will eventually use the `aaaa` event hub, not `bbbb`.
```yaml
spring:
  cloud:
    azure:
      eventhubs:
        namespace: evhns-sample
        event-hub-name: bbbb
        consumer:
          consumer-group: $Default
          event-hub-name: aaaa
        producer:
          event-hub-name: aaaa
```

But for the following code,
```java
    @Autowired
    private EventHubConsumerClient consumerClient;

    @Autowired
    private EventHubProducerClient producerClient;
    
    @Override
    public void run(String... args) throws Exception {
        LOGGER.info("Sending message using Event Hub producer client. ==> {}", producerClient.getEventHubName());
        producerClient.send(Arrays.asList(new EventData("Test event")));
        LOGGER.info("Sent message to Event Hub.");
        producerClient.close();

        TimeUnit.SECONDS.sleep(3);
        LOGGER.info("Receiving message using Event Hub consumer client. ==> {}", consumerClient.getEventHubName());
        String PARTITION_ID = "0";
        IterableStream<PartitionEvent> partitionEvents = consumerClient.receiveFromPartition(PARTITION_ID, 1,
            EventPosition.earliest());
        Iterator<PartitionEvent> iterator = partitionEvents.stream().iterator();
        if (iterator.hasNext()) {
            PartitionEvent pe = iterator.next();
            LOGGER.info("Received message: {}", pe.getData().getBodyAsString());
        } else {
            LOGGER.error("Failed to receive message.");
        }
    }
```

The application logs show that it still use `bbbb`, not the `aaaa`, which is inconsistent as above expectation.
```
Sending message using Event Hub producer client. ==> bbbb
....
Receiving message using Event Hub consumer client. ==> bbbb
```

***Exception or Stack Trace***
No exception, just inconsistent behavior.

**To Reproduce**

Run this repo code: https://github.com/[haoozhang/spring-cloud-azure-starter-eventhubs-sample](https://github.com/haoozhang/spring-cloud-azure-starter-eventhubs-sample)

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ] IDEA
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]  `spring-cloud-azure-starter-eventhubs` 5.18.0
 - Java version: [e.g. 8] 17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### LINKED ISSUE #46752: [BUG] [CRITICAL] Missing offset in checkpoint store
**Describe the bug**
After updating azure-sdk-bom to 1.2.38 offset is not stored anymore in Azure Blob Storage. 
This is not only breaking our monitoring but also partition switch is currently broken.

**To Reproduce**
Use azure-sdk-bom 1.2.38.
Observe `offset` is not stored anymore.

***Code Snippet***
This is caused by `offsetString` is not used in every place:
```
com.azure.messaging.eventhubs.models.EventContext#updateCheckpointAsync:
    public Mono<Void> updateCheckpointAsync() {
        if (eventData == null) {
            return Mono.empty();
        }
        Checkpoint checkpoint
            = new Checkpoint().setFullyQualifiedNamespace(partitionContext.getFullyQualifiedNamespace())
                .setEventHubName(partitionContext.getEventHubName())
                .setConsumerGroup(partitionContext.getConsumerGroup())
                .setPartitionId(partitionContext.getPartitionId())
                .setSequenceNumber(eventData.getSequenceNumber())
                .setOffset(eventData.getOffset());
        return this.checkpointStore.updateCheckpoint(checkpoint);
    }
```
But there should be a fallback in `com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore#updateCheckpoint` to use `getOffset()` when `getOffsetString()` returns null or empty until `getOffset()` is removed.

**Expected behavior**
`offset` is saved in Checkpoint store.

**Screenshots**
Image

**Setup (please complete the following information):**
 - Library/Libraries:
* azure-sdk-bom:1.2.38
* com.azure:azure-messaging-eventhubs-checkpointstore-blob:jar:1.21.0
* com.azure:azure-messaging-eventhubs:jar:5.21.0
 - Java version: 21 

**Severity**
This is a high critical defect, because it breaks partition switch and our grafana monitoring - we can't monitor consumer group lag.

### PR DESCRIPTION
**Pull request by j7nw4r**
Fixes #43593.
Fixes #46752.

This PR contains two related Event Hubs fixes that were developed together; they are kept in one PR because the second fix is required for any partition checkpoint that uses the sub-level `event-hub-name` override exercised by the first fix.

---

### Problem

When using `spring-cloud-azure-starter-eventhubs` with both base-level and sub-level `event-hub-name` configured:

```yaml
spring:
  cloud:
    azure:
      eventhubs:
        namespace: evhns-sample
        event-hub-name: bbbb
        consumer:
          consumer-group: $Default
          event-hub-name: aaaa
        producer:
          event-hub-name: aaaa
```

the injected `EventHubProducerClient` / `EventHubConsumerClient` connect to `bbbb` instead of the override `aaaa`.

### Root cause

The property merge in `AzureEventHubsProperties.build{Consumer,Producer}Properties()` is correct (sub-level wins). The defect is in the autoconfiguration path selection:

`AzureEventHubs{Consumer,Producer}ClientConfiguration` only switches to the *Dedicated* (per-section builder) inner configuration when `connection-string` or `namespace` is set under the sub-prefix. With only `event-hub-name` overridden, it falls through to the *Shared* configuration, which reuses the parent `EventHubClientBuilder` already pinned to `bbbb`. `EventHubClientBuilder` is per-hub, so the shared path cannot represent a different hub.

### Fix

Add `"event-hub-name"` to the `@ConditionalOnMissingProperty` / `@ConditionalOnAnyProperty` `name` arrays in both consumer and producer client configurations. Any sub-level `event-hub-name` override now routes to the Dedicated path, which already calls `build{Consumer,Producer}Properties()` with the correct precedence — no merge-logic changes required.

---

### Problem

`EventContext.updateCheckpointAsync()` only populated the deprecated `Checkpoint.offset` (Long) from the received `EventData`, leaving `offsetString` unset. Checkpoint stores that read `offsetString` (such as `BlobCheckpointStore`) then persisted a `null` offset, breaking partition switch-over and consumer-group lag monitoring.

### Fix

- `EventContext` now also propagates `EventData.getOffsetString()` onto the constructed `Checkpoint`.
- `BlobCheckpointStore.updateCheckpoint` now accepts `offsetString`-only checkpoints and prefers `offsetString` over the deprecated `offset` when both are populated. The validation guard was widened accordingly; the JavaDoc was updated to document the new contract.

---

## Tests

- Added `consumerEventHubNameOverrideShouldConfigureDedicated` and `producerEventHubNameOverrideShouldConfigureDedicated` reproducing the Spring issue scenario and asserting the merged properties resolve to the override and to the parent namespace.
- Pruned the obsolete sub-scenarios in `eventHubNameAndConsumerGroupProvidedShouldConfigure` / `eventHubNameProvidedShouldConfigure` that were asserting the old (buggy) behavior.
- Added `EventContextTest` coverage for `offsetString` propagation through `updateCheckpointAsync()`.
- Added `BlobCheckpointStoreTests` coverage for `offsetString`-only checkpoints, `offsetString`-preferred-over-`offset` precedence, and the widened validation guard.
- All affected modules' tests pass locally.

## How to verify

```
mvn -f sdk/spring/spring-cloud-azure-autoconfigure/pom.xml `
    -Dtest='AzureEventHubsConsumerClientConfigurationTests,AzureEventHubsProducerClientConfigurationTests,AzureEventHubsAutoConfigurationTests' `
    -DfailIfNoTests=false test

mvn -f sdk/eventhubs/azure-messaging-eventhubs/pom.xml -Dtest=EventContextTest -DfailIfNoTests=false test

mvn -f sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/pom.xml -Dtest=BlobCheckpointStoreTests -DfailIfNoTests=false test
```

### CODE REVIEW

File: sdk/spring/spring-cloud-azure-autoconfigure/CHANGELOG.md
Comment (rujche) [inline sdk/spring/spring-cloud-azure-autoconfigure/CHANGELOG.md]: Please revert the change in current file, move the new added change log item into `sdk/spring/CHANGELOG.md`.

**Review by rujche — APPROVED** [review]

File: sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsProducerClientConfiguration.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ EventHubProducerClient eventHubProducerClient(EventHubClientBuilder builder) {
         }
     }
 
-    @ConditionalOnAnyProperty(prefix = "spring.cloud.azure.eventhubs.producer", name = { "connection-string", "namespace" })
+    @ConditionalOnAnyProperty(prefix = "spring.cloud.azure.eventhubs.producer", name = { "connection-string", "namespace", "event-hub-name" })
     @Configuration(proxyBeanMethods = false)
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsProducerClientConfiguration.java:55]: Confirmed the cross-bean type ambiguity, but it's pre-existing: `DedicatedConsumer`/`DedicatedProducerConnectionConfiguration` already registered named-but-`EventHubClientBuilder`-typed beans whenever the user set a sub-level `connection-string` or `namespace`. Because `AzureEventHubsClientBuilderConfiguration#eventHubClientBuilder` is `@ConditionalOnMissingBean` *by type*, any dedicated builder suppresses the root, and the surviving shared path on the other side then resolves its unqualified `EventHubClientBuilder` parameter to the only remaining bean (the other section's dedicated one). This PR widens the trigger to `event-hub-name` but does not introduce the wiring flaw.

Note also that the *primary* Spring Messaging path (`AzureEventHubsMessagingAutoConfiguration` → `NamespaceProperties` → `DefaultEventHubsNamespaceProducerFactory`) does not depend on these client builder beans; it produces per-event-hub builders on demand from `NamespaceProperties`, so `EventHubsTemplate` and the processor container are unaffected. The concern is scoped to direct `EventHubProducerClient` / `EventHubConsumerClient` injection in mixed dedicated/shared mode.

Fixing this properly requires a broader change (e.g., naming the root builder and switching `@ConditionalOnMissingBean(EventHubClientBuilder.class)` to a name-based check, or marking the root `@Primary` and adding qualifiers on the shared injection points) plus regression coverage. I'll open a follow-up issue to track that rather than expand the scope of this PR, which @rujche has already approved as a tight fix for #43593.

File: sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java [hunk 2]
```diff
@@ -238,14 +238,22 @@ private Mono<PartitionOwnership> updateOwnershipETag(Response<?> response, Parti
...
      * Updates the checkpoint in Storage Blobs for a partition.
      *
-     * @param checkpoint Checkpoint information containing sequence number and offset to be stored for this partition.
+     * <p>At least one of {@code sequenceNumber}, {@code offsetString}, or the deprecated {@code offset} must be
+     * populated on the supplied {@link Checkpoint}. When both {@code offsetString} and the deprecated {@code offset}
+     * are populated, {@code offsetString} is preferred and persisted as the offset metadata value.</p>
+     *
+     * @param checkpoint Checkpoint information containing the sequence number and/or offset (as {@code offsetString}
+     * or the deprecated {@code offset}) to be stored for this partition.
      * @return The new ETag on successful update.
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java]: Fixed in 119c9f7. The `@return` tag now matches the actual `Mono<Void>` contract and mirrors the wording on the parent `CheckpointStore#updateCheckpoint` interface.

File: sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsProducerClientConfiguration.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsProducerClientConfiguration.java:55]: Follow-up tracked in #49245.

File: sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsConsumerClientConfiguration.java [hunk 3]
```diff
@@ -69,7 +69,7 @@ EventHubConsumerClient eventHubConsumerClient(EventHubClientBuilder builder) {
         }
     }
 
-    @ConditionalOnAnyProperty(prefix = "spring.cloud.azure.eventhubs.consumer", name = { "connection-string", "namespace" })
+    @ConditionalOnAnyProperty(prefix = "spring.cloud.azure.eventhubs.consumer", name = { "connection-string", "namespace", "event-hub-name" })
     @Configuration(proxyBeanMethods = false)
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/eventhubs/AzureEventHubsConsumerClientConfiguration.java:73]: Same root cause as the producer-side thread; see https://github.com/Azure/azure-sdk-for-java/pull/49076#discussion_r3289399810 for the analysis and #49245 for the follow-up. In short: this is a pre-existing wiring flaw (any dedicated builder, whether triggered by `connection-string`, `namespace`, or now `event-hub-name`, suppresses the type-conditional root and lets the opposite section's shared path bind to the wrong builder). Out of scope for this PR.

File: sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md [hunk 4]
```diff
@@ -8,6 +8,12 @@
 
 ### Bugs Fixed
 
+- Fixed `EventContext.updateCheckpointAsync()` so that the `offsetString` from the received `EventData` is propagated
+  to the `Checkpoint` passed to the `CheckpointStore`. Previously only the deprecated `offset` (Long) was set, which
+  caused checkpoint stores that read `offsetString` (such as `BlobCheckpointStore`) to persist a `null` offset, breaking
+  partition switch-over and consumer-group lag monitoring.
+  ([#46752](https://github.com/Azure/azure-sdk-for-java/issues/46752))
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md:15]: The PR title and description were updated to call out both fixes (the Spring sub-level override and the EventContext offsetString propagation) and explain why they're bundled (the second fix is required for any partition checkpoint that uses the sub-level event-hub-name override exercised by the first fix). Resolving.

File: sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/test/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStoreTests.java [hunk 5]
```diff
@@ -261,6 +263,107 @@ public void testUpdateCheckpointInvalid() {
...
+            .setPartitionId("0")
+            .setSequenceNumber(2L)
+            .setOffset(100L)
+            .setOffsetString("offset-string-value"));
+
+        assertEquals("offset-string-value", captured.get(OFFSET));
+    }
+
+    /**
+     * Tests that an offsetString-only checkpoint is accepted by the validation guard (preserving previous behavior).
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/test/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStoreTests.java]: Addressed in fc60d31. The test comment now explicitly notes the validation widening is a behavior change (prior implementation only inspected sequenceNumber/offset and would have rejected an offsetString-only checkpoint).

File: sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java [hunk 6]
```diff
@@ -243,9 +243,12 @@ private Mono<PartitionOwnership> updateOwnershipETag(Response<?> response, Parti
...
     public Mono<Void> updateCheckpoint(Checkpoint checkpoint) {
-        if (checkpoint == null || (checkpoint.getSequenceNumber() == null && checkpoint.getOffset() == null)) {
+        if (checkpoint == null
+            || (checkpoint.getSequenceNumber() == null
+                && checkpoint.getOffset() == null
+                && CoreUtils.isNullOrEmpty(checkpoint.getOffsetString()))) {
             throw LOGGER.logExceptionAsWarning(Exceptions.propagate(new IllegalStateException(
-                "Both sequence number and offset cannot be null when updating a checkpoint")));
+                "At least one of sequence number, offset, or offsetString must be provided when updating a checkpoint")));
         }
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java:257]: Addressed in fc60d31. The JavaDoc now documents that offsetString is a supported value and is preferred over the deprecated offset when both are populated.

**Review by SwayGom — COMMENTED** [review]
test

**Review by axisc — APPROVED** [review]
