### ISSUE TITLE
[BUG] Query annotation with ARRAY_CONTAINS not working in azure-spring-data-cosmos 3.26.0

### ISSUE THREAD

**Issue by SethuSaravanan** [Azure/azure-sdk-for-java#31023]
**Describe the bug**
@Query annotation with ARRAY_CONTAINS which was working fine in 3.25.0 of azure-spring-data-cosmos NOT working in 3.26.0

***Exception or Stack Trace***
```
{
  "status": "BAD_REQUEST",
  "message": "Error occurred",
  "errors": [
    "{\"innerErrorMessage\":\"Message: {\\\"errors\\\":[{\\\"severity\\\":\\\"Error\\\",\\\"location\\\":{\\\"start\\\":61,\\\"end\\\":62},\\\"code\\\":\\\"SC1001\\\",\\\"message\\\":\\\"Syntax error, incorrect syntax near ','.\\\"}]}\\r\\nActivityId: cc85d97a-9e14-46cd-9f02-b9f8f4b45641, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest\",\"cosmosDiagnostics\":{\"userAgent\":\"azsdk-java-cosmos/4.35.0 MacOSX/10.16 JRE/1.8.0_181\",\"activityId\":\"cc85d97a-9e14-46cd-9f02-b9f8f4b45641\",\"requestLatencyInMs\":893,\"requestStartTimeUTC\":\"2022-09-19T02:56:48.555Z\",\"requestEndTimeUTC\":\"2022-09-19T02:56:49.448Z\",\"responseStatisticsList\":[],\"supplementalResponseStatisticsList\":[],\"addressResolutionStatistics\":{},\"regionsContacted\":[\"west us 2\"],\"retryContext\":{\"statusAndSubStatusCodes\":null,\"retryCount\":0,\"retryLatency\":0},\"metadataDiagnosticsContext\":{\"metadataDiagnosticList\":null},\"serializationDiagnosticsContext\":{\"serializationDiagnosticsList\":null},\"gatewayStatistics\":{\"sessionToken\":null,\"operationType\":\"QueryPlan\",\"resourceType\":\"Document\",\"statusCode\":400,\"subStatusCode\":0,\"requestCharge\":0.0,\"requestTimeline\":[{\"eventName\":\"connectionCreated\",\"startTimeUTC\":\"2022-09-19T02:56:48.556Z\",\"durationInMilliSecs\":808.0},{\"eventName\":\"connectionConfigured\",\"startTimeUTC\":\"2022-09-19T02:56:49.364Z\",\"durationInMilliSecs\":0.0},{\"eventName\":\"requestSent\",\"startTimeUTC\":\"2022-09-19T02:56:49.364Z\",\"durationInMilliSecs\":1.0},{\"eventName\":\"transitTime\",\"startTimeUTC\":\"2022-09-19T02:56:49.365Z\",\"durationInMilliSecs\":82.0},{\"eventName\":\"received\",\"startTimeUTC\":\"2022-09-19T02:56:49.447Z\",\"durationInMilliSecs\":0.0}],\"partitionKeyRangeId\":null,\"exceptionMessage\":\"Message: {\\\"errors\\\":[{\\\"severity\\\":\\\"Error\\\",\\\"location\\\":{\\\"start\\\":61,\\\"end\\\":62},\\\"code\\\":\\\"SC1001\\\",\\\"message\\\":\\\"Syntax error, incorrect syntax near ','.\\\"}]}\\r\\nActivityId: cc85d97a-9e14-46cd-9f02-b9f8f4b45641, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest\",\"exceptionResponseHeaders\":\"{Content-Type=application/json, Date=Mon, 19 Sep 2022 02:56:51 GMT, Server=Microsoft-HTTPAPI/2.0, Strict-Transport-Security=max-age=31536000, Transfer-Encoding=chunked, x-ms-activity-id=cc85d97a-9e14-46cd-9f02-b9f8f4b45641, x-ms-gatewayversion=version=2.14.0}\"},\"systemInformation\":{\"usedMemory\":\"289122 KB\",\"availableMemory\":\"3439262 KB\",\"systemCpuLoad\":\"(2022-09-19T02:56:23.516Z 20.3%), (2022-09-19T02:56:28.513Z 32.5%), (2022-09-19T02:56:33.513Z 32.8%), (2022-09-19T02:56:38.515Z 24.2%), (2022-09-19T02:56:43.515Z 30.6%), (2022-09-19T02:56:48.514Z 29.3%)\",\"availableProcessors\":8},\"clientCfgs\":{\"id\":1,\"machineId\":\"uuid:73773743-6b1c-413d-bc67-f26d3e17859c\",\"connectionMode\":\"DIRECT\",\"numberOfClients\":2,\"connCfg\":{\"rntbd\":\"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)\",\"gw\":\"(cps:1000, nrto:PT1M, icto:PT1M, p:false)\",\"other\":\"(ed: true, cs: false)\"},\"consistencyCfg\":\"(consistency: Strong, mm: true, prgns: [])\"}}}"
  ]
}
```

**To Reproduce**
1. add 3.26.0 to pom.xml
2. Call method with @Query annotation in a repository which has ARRAY_CONTAINS 

***Code Snippet***
We were using azure-spring-data-cosmos 3.25.0 for our api.

```xml
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.25.0</version>
        </dependency>

```
and below query was yielding expected results with out any issues for given tenantId , one or more region string as input.

```java
        @Query(value = "SELECT * FROM at "
                  + "WHERE at.tenantId = @tenantId "
                  + "AND (@regions = null or ARRAY_CONTAINS(@regions, at.region)) ")
        List<ArchiveTransaction> findAllArchiveTransByRegions(
                  @Param("tenantId") String tenantId,
                  @Param("regions") List<String> regions);

```
But when we upgraded our version to 3.26.0 it is returning data only for given tenentId and no region.
It is NOT returning any data for given tenentId and one or more region as input.

```java
        @Query(value = "SELECT * FROM at "
                  + "WHERE at.tenantId = @tenantId "
                  + "AND (@regions = null or ARRAY_CONTAINS([@regions], at.region)) ")
        List<ArchiveTransaction> findAllArchiveTransByRegions(
                  @Param("tenantId") String tenantId,
                  @Param("regions") List<String> regions);

```
we had to change the query to include square brackets around @Regions like [@Regions] for it to work.
Even with that change it works only for a single input tenentId and single input of region , when we input two or more region as input the query is failing with error " Syntax error, incorrect syntax near ','. ". Please see above for the full exception message.

Looks like this bug was introduced in 3.26.0 , please fix it.

**Expected behavior**
@query annotation should work with out the need of square brackets around the element which uses ARRAY_CONTAINS and should return records with out any syntax error. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-data-cosmos:3.26.0 (groupId:com.azure)]
 - Java version: 8 
 - App Server/Environment: Tomcat 
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by saragluna** [comment]
@kushagraThapar, @xinlian12, @FabianMeiswinkel could you help take a look at this?

**Comment by kushagraThapar** [comment]
@trande4884 is already working on this, assigning correctly.
