### ISSUE TITLE
[BUG] spring-cloud-azure-appconfiguration-config v1.2.9 does not work with Spring Boot 1.5

### ISSUE THREAD

**Issue by Ramblurr** [Azure/azure-sdk-for-java#23425]
**Describe the bug**

Version 1.2.9 of the XX depends on `org.springframework.cloud:spring-cloud-context`, and uses [annotations](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/Nullable.html) which are only available in spring > 2.0.

***Exception or Stack Trace***

This stacktrace is the result of `org.springframework.cloud:spring-cloud-context` 2.2.5.RELEASE being included, which won't work in Spring Boot 1.5.x

```
09:32:16.331 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Class;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:186)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:135)
```

**To Reproduce**

We have a spring boot project using version 1.5 of spring boot. The  documentation on [this page](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app#create-a-spring-boot-app) instructs me to use version 1.2.9 of the appconfiguration library.

We include the library like so:
```
    compile("com.microsoft.azure:spring-cloud-azure-appconfiguration-config:1.2.9")
```

***Code Snippet***

**Expected behavior**

I expected the "older versions" message in the docs to lead to a version that would work with 1.5.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: Intellij
 - Library/Libraries: com.microsoft.azure:spring-cloud-azure-appconfiguration-config:1.2.9
 - Java version: 8
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

```
..snip..
--- com.microsoft.azure:spring-cloud-azure-appconfiguration-config:1.2.9
     +--- org.springframework.boot:spring-boot-autoconfigure-processor:2.3.5.RELEASE -> 1.5.22.RELEASE
     +--- org.springframework.boot:spring-boot-autoconfigure:2.3.5.RELEASE -> 1.5.22.RELEASE (*)
     +--- org.springframework.cloud:spring-cloud-context:2.2.5.RELEASE
     |    \--- org.springframework.security:spring-security-crypto:5.3.3.RELEASE -> 4.2.13.RELEASE
     +--- com.fasterxml.jackson.core:jackson-annotations:2.12.1 -> 2.8.0
     +--- com.fasterxml.jackson.core:jackson-databind:2.12.1 -> 2.8.11.3 (*)
     +--- org.springframework:spring-web:5.2.10.RELEASE -> 4.3.25.RELEASE (*)
     +--- com.azure:azure-core:1.13.0
... snip ..
```
  
**Additional context**

I assumed the link to the older versions would support 1.5. But maybe < 2.0 simply isn't supported? If that is the case it would be very helpful to explicitly list which version ranges of spring boot are supported.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@saragluna @backwind1233 could you please assist @Ramblurr on this issue?

**Comment by Ramblurr** [comment]
> @Ramblurr Have you tried the 1.3.0 version? That was updated to work with 2.4 and should also work with 2.5.

I have yes, and it doesn't work because the project I want to integrate it into is on Spring Boot < 2.4 (It is actually two projects. One is on spring boot 1.5 and the other is spring boot 2.3).

It would be nice if the documentation could be updated to specifically list the supported spring boot versions (or the minimum spring boot version).

/unresolve

**Comment by mrm9084** [comment]
@Ramblurr 1.3.0 is compatible with  Spring Boot 2.4 and 2.5. 1.2.9 is compatible with Spring Boot 2.3.

You can find the dependency version info here https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-azure-appconfiguration-config/1.3.0.

Are you looking for a version that works with Spring Boot 2.3 and 2.4? If so I don't think you will find it as there was breaking changes between those two Spring Boot Versions.

**Comment by Ramblurr** [comment]
I was looking for a version compatible with spring boot 1.5, but that doesn't exist (which is understandable, 1.5 is very old).

But it would be nice if [the documentation ](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app#create-a-spring-boot-app) could be updated to specifically mention the supported spring-boot versions.

This message here is too vague to be useful:

![image](https://user-images.githubusercontent.com/14830/134476977-2adc5bda-4ac8-453d-806e-909406e8ad4d.png)

**Comment by mrm9084** [comment]
@Ramblurr I think the oldest version we ever released for was Spring Boot 2.2. It you need older support you can try to use the Azure SDK, though you may run into dependency issues.

Also, there is a REST API, https://docs.microsoft.com/azure/azure-app-configuration/rest-api

**Comment by mrm9084** [comment]
I think this should be good to be closed. Re-open it or make a new issue if you have any additional questions.
